package io.ilyahaker.sokobanserver.objects;

public enum Material {
    OAK_WOOD, OAK_PLANKS, PLAYER_HEAD, STONE_BRICKS, BARRIER, WHITE_SHULKER_BOX, LIME_STAINED_GLASS_PANE,
    PURPLE_STAINED_GLASS, RED_STAINED_GLASS, PAPER, MAGENTA_STAINED_GLASS
}
